openapi: 3.0.3
info:
  title: API de Contatos
  version: 1.0.0
  description: Aplicação para gerenciamento de contatos de pessoas e organizações
  contact:
    email: samarasantosti@gmail.com
    name: Samara Santos
servers:
  - url: http://localhost:5500
    variables: {}
    description: Servidor local
paths:
  /pessoas:
    summary: Manipular informações relacionadas as pessoas da aplicação
    get:
      summary: Listar pessoas cadastradas
      tags:
        - Pessoas
      description: "Retorna um array de pessoas"
      operationId: listaPessoas
      parameters:
        - in: query
          name: search
          description: Texto a ser procurado no nome das pessoas
          schema:
            type: string
        - in: query
          name: order
          description: Critério de ordenação dos resultados (ascendente | descedente)
          schema:
            type: string
            enum:
              - asc
              - desc
        - in: query
          name: tags
          description: Tags a serem procuradas nas pessoas cadastradas
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: Operação bem sucedida
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pessoa"
    post:
      summary: Cadastrar uma pessoa
      tags:
        - Pessoas
      description: ""
      operationId: inserePessoa
      requestBody:
        description: "Pessoa a ser inserida"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pessoa"
      responses:
        201:
          description: Recurso inserido com sucesso
  /pessoas/{id}:
    get:
      summary: Obter uma pessoa pelo ID
      tags:
        - Pessoas
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
      requestBody:
        description: "Pessoa a ser alterada"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pessoa"
      responses:
        200:
          description: Operação bem sucedida
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pessoa"
        404:
          description: Pessoa não encontrada
    put:
      summary: Alterar uma pessoa específica por meio do ID
      operationId: alteraPessoa
      tags:
        - Pessoas
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
      responses:
        "204":
          description: Recurso alterado com sucesso
        "400":
          description: Erro ao alterar o recurso no servidor
    delete:
      summary: Alterar uma pessoa específica por meio do ID
      tags:
        - Pessoas
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: integer
      responses:
        204:
          description: Recurso excluído com sucesso
        400:
          description: Erro ao excluir o recurso no servidor
components:
  schemas:
    Pessoa:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
          description: Nome da pessoa
        email:
          type: string
          description: Endereço eletrônico da pessoa
        telefone:
          type: string
          description: Número de telefone da pessoa
        tags:
          type: array
          items:
            type: string
            description: Tags
      required:
        - nome
        - email
    Organizacao:
      title: Organizacao
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        segmento:
          type: string
        endereco:
          type: string
        cidade:
          type: string
        cep:
          type: string
        estado:
          type: string
        telefones:
          type: array
          items:
            type: string
      required:
        - nome
        - segmento
      example:
        id: 1
        nome: Acme Corporation
        segmento: Varejo
        endereco: Av. Rebolças, 422 - Centro
        cidade: São Paulo
        cep: 33422-990
        estado: SP
        telefones: ["11-3234-5543", "11-4425-5544"]
